version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mobility_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pgdata:
